name: main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  build_matrix:
    strategy:
      matrix:
        os: [ubuntu-latest]
      
    runs-on: ${{ matrix.os }}
    
    env:
      app_name: app_${{ matrix.os }}_${{ github.ref_name }}_${{ github.run_number }}
    
    steps:
      - uses: actions/checkout@v3
    
      - name: Build_test_file
        run: g++ test.cpp -o ${{ env.app_name }}
        
  send_to_tg:
      needs: build_matrix
      runs-on: ubuntu-latest
      
      env:
        app_name: app_${{ github.ref_name }}_${{ github.run_number }}
      
      steps: 
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: my-artifact
          retention-days: 10
      
      - name: if_something_wrong
        if: ${{ failure() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHANNEL_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: App build was wrong
      
      - name: Send_to_Telegramm
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHANNEL_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            There was a ${{ github.event_name }} by ${{ github.actor }} 
            in the repository ${{ github.repository }}
          document: my-artifact/**
