name: main

on:
  push:
    branches: [ "main" ]
  pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3
        
      - name: Build_server
        run: g++ test.cpp -o app
