name: main

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:


jobs:

  build_matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
      
    runs-on: ${{ matrix.os }}
    
    env:
      app_name: app_${{ matrix.os }}_${{ github.run_number }}
      
    steps:
      - uses: actions/checkout@v3
    
      - name: Build_test_file
        run: g++ test.cpp -o ${{ env.app_name }}
        
      - name: Upload_Areifacts
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: ${{ env.app_name }}**
          retention-days: 10
