name: main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:

env:
  app_name: app_${{ github.run_number }}_${{ githib.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
    
      - name: Build_test_file
        run: g++ test.cpp -o ${{ env.app_name }}_${{ matrix.os }}
        
      - name: Upload_Areifacts
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: ${{ env.app_name }}_${{ matrix.os }}
          retention-days: 10
          
      - name: Send_to_Telegramm
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHANNEL_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: There was a ${{ github.event_name }} by ${{ github.actor }} in the repository ${{ github.repository }}
          document: ${{ env.app_name }}_${{ matrix.os }}
