name: main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  build_matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      
    runs-on: ${{ matrix.os }}
    
    env:
      app_name: ${{ matrix.os }}_${{ github.ref_name }}_${{ github.run_number }}_app
    
    steps:
      - uses: actions/checkout@v3
    
      - name: Build_test_file
        run: g++ test.cpp -o ${{ env.app_name }}
        
      - name: Upload_artifacts
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: ${{ env.app_name }}**
          retention-days: 10
        
  send_to_tg:
      runs-on: ubuntu-latest
      
      env:
        app_name: ${{ github.ref_name }}_${{ github.run_number }}_app
      
      steps: 
      - uses: actions/download-artifact@v3
        with:
          name: my-artifact
          path: my-artifact
             
      - name: Send_to_Telegramm
        if: ${{ always() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHANNEL_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            ${{ github.actor }} created ${{ github.event_name }}:
            Commit message: ${{ github.event.commits[0].message }}
            Repository: ${{ github.repository }}
            Status: ${{ job.status }}
          document: my-artifact/**
