name: main

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build_ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
    
      - name: Build_test_file
        run: g++ test.cpp -o app_ubuntu
        
      - name: Upload_Areifacts
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: app_ubuntu
          retention-days: 1
          
  build_windows:
    runs-on: windows-latest
    
    steps:
    
      - name: Setup C/C++ Compiler
        uses: rlalik/setup-cpp-compiler@v1.1
        with:
          compiler: gcc-latest

      - uses: actions/checkout@v3
    
      - name: Build_test_file_1
        run: gcc ./test.cpp
        
      - name: Upload_Areifacts
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: app_windows
          retention-days: 1
